version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - godox
    - paralleltest
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com
            - golang.org
            - google.golang.org
    lll:
      line-length: 140
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
        path: (.+)_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/gripmock)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
